# Generated by Django 4.1.3 on 2023-02-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_shippingaddress_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кол-во'),
        ),
    ]
